name: common

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_call:  # avail for other pipeline to ref


jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0  # key needed to GitVersion tool
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    
    - name: Restore dependencies
      run: dotnet restore --locked-mode
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Test  # GitVersion takes effect here with pushed tags in Release pipeline
      run: dotnet test --no-build --configuration Release --verbosity normal

    - name: Pack
      run: dotnet pack --no-build --configuration Release --output package2  # results package.nupkg

    - name: Publish
      run: dotnet publish -c Release -o package
        
    - name: Package published artifact
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: package/*
        if-no-files-found: error
