name: common

on:
  workflow_call:
    
jobs:
  build:

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'

    - name: Determine Version
      id: gitversion # step id used as reference for output values
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true
        configFilePath: GitVersion.yml
        
    - name: Display GitVersion outputs
      run: |
        echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"
        echo "InformationalVersion: ${{ steps.gitversion.outputs.informationalVersion }}"

    - name: Restore dependencies
      run: dotnet restore --locked-mode
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal

    - name: Create archive files
      run: |
        mkdir package
        cd package
        echo 'one' > one.txt
        echo 'two' > two.txt
        cd ..
        
    - name: Package build artifact
      uses: actions/upload-artifact@v2
      with:
        name: versioningDemo-${{ steps.gitversion.outputs.semVer }}
        path: package/*
        if-no-files-found: error
