
name: Continuous

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    uses: ./.github/workflows/common.yml
    # uses: ./.github/workflows/common-continuous.yml ## useable since common-continuous.yml has the 'workflow_call' property
