
name: Release

on:
  push:
     tags: [ "v[0-9]+.[0-9]+.[0-9]+*" ]

jobs:
  build:
    uses: ./.github/workflows/common.yml

  nuget-push:
    runs-on:  windows-2022 # windows-latest....dotnet 6 uses -2022
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: package   # download artifact w/ this name, into same folder name

      - name: Publish to nuget
        run: echo "Publishing..."
        # run: dotnet nuget push "./package/*.nupkg" --no-symbols true --source "https://api.nuget.org/v3/index.json" --api-key ${{ secrets.NUGET_KEY }}
