
name: Release

on:
  push:
     tags: [ "v[0-9]+.[0-9]+.[0-9]+" ]

jobs:
  build:
    uses: ./.github/workflows/common.yml

  nuget-push:
    runs-on:  windows-2022 # windows-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: package

      - name: Publish to nuget
        run: echo "Publish..."
