
name: Release

on:
  push:
     tags: [ "v[0-9]+.[0-9]+.[0-9]+" ]

jobs:
  build:
    uses: ./.github/workflows/common.yml

  nuget-push:
    runs-on:  windows-2022
    # runs-on:  windows-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: versioningDemo
          path: ./package
          # name: package


      - name: Display structure of downloaded files
        run: ls -R

      - name: Publish to nuget
        run: echo "Publish..."

      # - name: Display structure of downloaded files
      #   run: ls -R
